name: Publish with Gradle

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Which repository should be published to?"
        required: true
        default: "releases"
        type: choice
        options:
          - "Releases"
          - "Snapshots"
      git-versioning:
        description: "Should the version be updated with Git information?"
        required: true
        default: "true"
        type: choice
        options:
          - "Yes"
          - "No"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Gradle
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Maven
        env:
          DEFTU_PUBLISHING_USERNAME: ${{ secrets.DEFTU_PUBLISHING_USERNAME }}
          DEFTU_PUBLISHING_PASSWORD: ${{ secrets.DEFTU_PUBLISHING_PASSWORD }}
        run: ./gradlew publishAllPublicationsToDeftu${{ github.event.inputs.repository }}Repository -Pgitdata.version=${{ github.event.inputs.git-versioning == 'Yes' }}

      - name: Publish to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishProjectToGitHub -Pgitdata.version=${{ github.event.inputs.git-versioning == 'Yes' }}
