name: Publish with Gradle

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Which repository should be published to?"
        required: true
        default: "releases"
        type: choice
        options:
          - "Releases"
          - "Snapshots"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Gradle
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
